name: "AWS Runner Infra"

on:
  workflow_dispatch: 



jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./project/terraform/aws-runner/

    steps:
      # Checkout repo
      - uses: actions/checkout@v3



      # Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: 'us-east-1'


      - name: Install AWS CLI v2
        run:  |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/
          export AWS_REGION=us-east-1  # Change this to your desired region
          aws ssm get-parameter --name "ssh_key" --query "Parameter.Value" --output text --region $AWS_REGION >> aws.pem


      #  Add SSH Key from GitHub Secrets
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" >> ~/.ssh/authorized_keys
          chmod 600 ./aws.pem

      # Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve


      # Save instance IPs and create inventory file for Ansible
      - name: Save instance IPs and create inventory
        run: |
          INSTANCE_IPS=$(terraform output -json python_vm_public_ip)

          # Check if it's a JSON array or a string
          if echo "$INSTANCE_IPS" | jq -e 'if type == "string" then empty else . end' >/dev/null; then
            IP_LIST=$(echo "$INSTANCE_IPS" | jq -r '.[]')
          else
            IP_LIST=$(echo "$INSTANCE_IPS" | jq -r '.')
          fi

          # Create inventory.ini
          echo "[servers]" > inventory.ini
          echo "$IP_LIST ansible_user=ubuntu ansible_ssh_private_key_file=./aws.pem" >> inventory.ini


      # Wait for SSH to be available
      - name: Wait for SSH to be available
        run: |
          for ip in $(cat instance-ips.txt); do
            echo "⏳ Waiting for SSH on $ip..."
            SECONDS=0
            while ! nc -z $ip 22; do
              sleep 10
              if [ $SECONDS -gt 300 ]; then
                echo "❌ Timeout: SSH is not available on $ip after 5 minutes."
                exit 1
              fi
            done
            echo "✅ SSH is available on $ip!"
          done



      # Test SSH connection
      - name: Check SSH Key
        run: |
          if [ ! -f ./aws.pem ]; then
            echo "ERROR: SSH key not found!"
            exit 1
          fi
          ls -l ./aws.pem

      - name: Set correct permissions for SSH key
        run: chmod 600 ./aws.pem

      - name: Check SSH Key Format
        run: |
          sudo apt-get install libssl-dev
          cat ./aws.pem
          ssh-keygen -l -f ./aws.pem || echo "Invalid SSH key!"

      - name: Convert SSH key to RSA format
        run: ssh-keygen -p -m PEM -f ./aws.pem -o -P "" -N ""

      - name: Test SSH connection
        run: |
          INSTANCE_IP=$(terraform output -json python_vm_public_ip | jq -r 'if type == "string" then . else .[0] end')

          echo "Trying to SSH into $INSTANCE_IP"
          ssh -vvv -o StrictHostKeyChecking=no -i ./aws.pem ubuntu@$INSTANCE_IP

